import { Article } from "@/components/blog/article";
import { Header } from "@/components/header";
import { Menu } from "@/components/menu";
import { ArticleService } from "@/service/articles";
import { Article as ArticleType } from "@/types/articles";
import type { GetStaticPaths, GetStaticProps, NextPage } from "next";
import Head from "next/head";
interface PageProps {
  article: ArticleType;
}

const Page: NextPage<PageProps> = ({ article }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Menu />
      <Article article={article} variant="blog"/>
    </>
  );
};

export const getStaticPaths: GetStaticPaths = async ({}) => {
  const { data: articles } = await ArticleService.getAllArticles();
  const paths = articles.articles.map((article) => ({ params: { slug: article.slug } }));
  return {
    paths,
    fallback: "blocking",
  };
};

export const getStaticProps: GetStaticProps = async (ctx) => {
  const slug = ctx.params!.slug
  const res = await ArticleService.getArticleBySlug(`${slug}`);
  return {
    props: {
      article: res.data.article,
      revalidate: 5,
    },
  };
};

export default Page;
