import type { GetStaticProps, NextPage } from "next";
import { Header } from "@/components/header";
import { Welcome } from "@/components/welcome";
import Head from "next/head";
import { Cars } from "@/components/cars";
import { Footer } from "@/components/footer";
import { Reason } from "@/components/reason";
import { Guarantees } from "@/components/guarantees";
import { Purchase } from "@/components/purchase";
import { Workflow } from "@/components/workflow";
import { ClientFeedback } from "@/components/clientFeedback";
import { Button } from "@/components/button";
import { Reviews } from "@/components/reviews";
import { Blog } from "@/components/blog";
import { ButtonBlog } from "@/components/buttonBlog";
import { Contacts } from "@/components/contacts";
import { CustomsBroker } from "@/components/customsBroker";
import { Picture } from "@/components/picture";
import { Menu } from "@/components/menu";
import { CarEvaluation } from "@/components/carEvaluation";
import { ArticleService } from "@/service/articles";
import { Article } from "@/types/articles";
import { BlogItems } from "@/components/blog/blog-articles";
import { HeaderService } from "@/service/header";
import { Header as HeaderProps } from "@/types/header";

interface PageProps {
  articles: Article[];
  headerData: HeaderProps;
}

const Page: NextPage<PageProps> = ({ articles, headerData }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header headerData={headerData} />
      <Menu />
      <Welcome />
      <Cars />
      <Reason />
      <Picture />
      <CustomsBroker />
      <Purchase />
      <Workflow />
      <ClientFeedback />
      <Button />
      <Reviews />
      <Blog />
      <ButtonBlog />
      <Contacts />
      <CarEvaluation />
      <BlogItems variant="home" articles={articles} title="Блог" />
      <Footer />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const res = await ArticleService.getAllArticles();
  const { data: headerData } = await HeaderService.getHeader();
  return {
    props: {
      articles: res.data.articles,
      headerData: headerData.headers[0],
      revalidate: 5,
    },
  };
};

export default Page;
