import { ArticleService } from "@/service/articles";
import { Article } from "@/types/articles";
import type { GetServerSideProps, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
interface PageProps {
  articles: Article[];
}

const Page: NextPage<PageProps> = ({ articles }) => {
  console.log(articles);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {articles.map((article) => {
          return (
            <Link key={article.id} href={`/news/${article.slug}`}>
              {article.title}
            </Link>
          );
        })}
      </div>
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const res = await ArticleService.getAllArticles();
  return {
    props: {
      articles: res.data.articles,
      revalidate: 5,
    },
  };
};

export default Page;
